id: I83391B3B
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:05:01.084742'
last_modified: '2022-05-31T05:05:01.084751'
parser: null
source_metadata:
  title: Lochen Chönyi Zangmo
  language: en
  description: 'Texts by and about Jetsün Lochen Chönyi Zangmo (lo chen chos nyid
    bzang mo, 1853/1865–1950/1951) of Shukseb (shug gseb), one of the most celebrated
    yoginīs of the last century:'
  volume:
    fCBB6:
      title: Guru Yoga of Jetsün Lochen, Queen of Yoginīs
      base_file: fCBB6.txt
      order: 1
      parent: Guru Yoga
    fB534:
      title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
      base_file: fB534.txt
      order: 2
      parent: Long Life Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
